#!/usr/bin/env python3
"""Validate deterministic TPHIP GET_CAPABILITIES request and response vectors."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REQUEST_PATH = ROOT / "samples" / "tphip_get_capabilities_request_v1.hex"
RESPONSE_PATH = ROOT / "samples" / "tphip_get_capabilities_response_v1.hex"


def crc16_ccitt_false(data: bytes) -> int:
    crc = 0xFFFF
    for value in data:
        crc ^= value << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc


def frame_crc(frame: bytes) -> int:
    work = bytearray(frame)
    work[14:16] = b"\x00\x00"
    return crc16_ccitt_false(bytes(work))


def load_hex(path: Path) -> bytes:
    tokens = path.read_text(encoding="utf-8").split()
    return bytes(int(token, 16) for token in tokens)


def build_request() -> bytes:
    frame = bytearray.fromhex("54 50 47 57 01 10 01 00 01 00 00 00 00 00 00 00")
    frame[14:16] = frame_crc(frame).to_bytes(2, "little")
    return bytes(frame)


def build_response() -> bytes:
    frame = bytearray.fromhex(
        "54 50 47 57 01 10 81 01 01 00 00 00 10 00 00 00 "
        "01 00 0C 00 40 00 00 00 00 00 00 00 01 00 01 00"
    )
    frame[14:16] = frame_crc(frame).to_bytes(2, "little")
    return bytes(frame)


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(f"FAIL: {message}")
    print(f"PASS: {message}")


def main() -> int:
    request = load_hex(REQUEST_PATH)
    response = load_hex(RESPONSE_PATH)

    require(len(request) == 16, "request vector is exactly 16 bytes")
    require(len(response) == 32, "response vector is exactly 32 bytes")
    require(request == build_request(), "request vector matches generated bytes")
    require(response == build_response(), "response vector matches generated bytes")
    require(int.from_bytes(request[14:16], "little") == 0x8272, "request CRC is 0x8272")
    require(int.from_bytes(response[14:16], "little") == 0xFE2D, "response CRC is 0xFE2D")
    require(request[8:10] == response[8:10] == b"\x01\x00", "sequence is echoed")
    require(response[12:14] == b"\x10\x00", "capabilities payload length is 16")
    require(response[18:20] == b"\x0c\x00", "advertised capability flags are 0x000c")

    print("TPHIP golden vectors passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())